tuning failover script

diff --git a/bin/failover b/bin/failover
--- a/bin/failover
+++ b/bin/failover
@@ -4,6 +4,14 @@
 # crontab -e
 # */1 * * * * /bin/failover
 
+# check if cronjob already exists
+crontab -l | grep failover > /dev/null
+if [ $? -ne 0 ]; then
+	# if not, add cronjob
+	echo "*/1 * * * * /bin/failover" >> /etc/crontab
+fi
+
+# ping the server we want to replace
 ping -q -c4 192.0.0.2 > /dev/null
 
 # was ping succesful?
@@ -15,6 +23,7 @@ else
 	# set up network
 	# eth1 for NW-1
 	ifconfig eth1 192.0.0.1 netmask 248.0.0.0
+	# necessary ?
 	route add -net 192.0.0.0 netmask 248.0.0.0 gw 128.0.0.2 dev eth1
 	# eth0 for NW-0
 	ifconfig eth0 128.0.0.2 netmask 240.0.0.0
